# This workflow will do a clean install of node dependencies, and run the linter and tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # Any additional branches here will currently be treated as release (or maintenance) branches.
  # if the need to run jobs on other branches emerges, then the release job will need a better
  # condition expression.
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    # https://github.community/t/github-actions-does-not-respect-skip-ci/17325/9
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]
        include:
          - node-version: 18.x
            report-coverage: true

    steps:
      - uses: actions/checkout@v2
        with:
          # For commitlint; ideally this would only check out the feature branch's history, but
          # that's not currently an option.
          fetch-depth: ${{ github.event_name == 'push' }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Use Node.js ${{ matrix.node-version }} for dependencies
        uses: actions/setup-node@v1
        if: '!steps.cache.outputs.cache-hit'
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        if: '!steps.cache.outputs.cache-hit'
        run: npm ci
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run ci --if-present
        env:
          BEE_QUEUE_TEST_REDIS: redis://localhost:6379
      - run: npm run ci:commitlint
        if: "github.event_name != 'push' && github.actor != 'dependabot[bot]'"
        env:
          GITHUB_BASE_REF: ${{ github.event.pull_request.base.ref }}
      - name: Report to Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.report-coverage
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    # https://github.community/t/github-actions-does-not-respect-skip-ci/17325/9
    if: "github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    needs: [test]

    steps:
      - uses: actions/checkout@v2
        with:
          # Necessary to prevent the checkout action from writing credentials to .git/config, which
          # semantic-release attempts to use to push despite those credentials being denied the
          # push.
          # See https://github.com/semantic-release/git/issues/196#issuecomment-601310576.
          persist-credentials: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Restore dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Release
        run: npx --no-install semantic-release
        env:
          # Need to use a separate token so we can push to the protected default branch.
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
